version: "3.7"

services:
  db:
    build:
      context: ./apps/db
      dockerfile: ./Dockerfile
    image: budipest/db:0.0.2
    container_name: budipest_db
    ports:
      - 5437:5432
    stdin_open: true
    tty: true
    volumes:
      - ./apps/db/backups:/.tmp
    env_file:
      - ./apps/db/config/.env

  db_test:
    build:
      context: ./apps/db
      dockerfile: ./Dockerfile
    image: budipest/db-test:0.0.2
    container_name: budipest_db_test
    ports:
      - 5438:5432
    stdin_open: true
    tty: true
    env_file:
      - ./apps/db/config/pipeline.env

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: budipest/api:0.0.2
    container_name: budipest_api
    ports:
      - 3100:3000
      - 9229:9229
    stdin_open: true
    tty: true
    volumes:
      - ./apps/api:/opt/code
      - /opt/code/node_modules
    environment:
      - ENVIRONMENT=development
      - PROD=false
      - HTTPS=false
      - APP_ID=budipest-backend
      - PORT=3000
      - DB_USER=budipest
      - DB_PASS=bdpst1234
      - DB_NAME=budipest_development
      - DB_HOST=budipest_db
      - DB_PORT=5432

    depends_on:
      - db
      # - db_test

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    image: budipest/admin:0.0.2
    container_name: budipest_admin
    volumes:
      - ./apps/admin:/opt/code
      - /opt/code/node_modules
    ports:
      - 3101:3001
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - PORT=3001

  landing:
    build:
      context: ./apps/landing
      dockerfile: Dockerfile
    image: budipest/landing:0.0.2
    container_name: budipest_landing
    volumes:
      - ./apps/landing:/opt/code
    ports:
      - 8081:80
    stdin_open: true
    tty: true
